// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TechCorner_ECommerce.Data;

#nullable disable

namespace TechCorner_ECommerce.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260411125405_bbb")]
    partial class bbb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TechCorner_ECommerce.Data.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 2,
                            Name = "PC"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Main - CPU - VGA"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gaming Gear"
                        });
                });

            modelBuilder.Entity("TechCorner_ECommerce.Data.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TechCorner_ECommerce.Data.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("TechCorner_ECommerce.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.Property<int>("SubCategoryId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SubCategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Gaming laptop RTX 3050",
                            ImageUrl = "acer_nitro5.jpg",
                            Name = "Acer Nitro 5",
                            Price = 1200.0,
                            Stock = 10,
                            SubCategoryId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "High performance gaming laptop",
                            ImageUrl = "asus_rog_g15.jpg",
                            Name = "Asus ROG Strix G15",
                            Price = 1500.0,
                            Stock = 8,
                            SubCategoryId = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Gaming laptop RTX 3060",
                            ImageUrl = "msi_katana.jpg",
                            Name = "MSI Katana GF66",
                            Price = 1400.0,
                            Stock = 6,
                            SubCategoryId = 3
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Custom build gaming PC",
                            ImageUrl = "pc_gaming.jpg",
                            Name = "Gaming PC RTX 4060",
                            Price = 2000.0,
                            Stock = 5,
                            SubCategoryId = 5
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "13th Gen CPU",
                            ImageUrl = "cpu_i7.jpg",
                            Name = "Intel Core i7 13700K",
                            Price = 450.0,
                            Stock = 15,
                            SubCategoryId = 8
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "NVIDIA Graphics Card",
                            ImageUrl = "rtx4070.jpg",
                            Name = "RTX 4070",
                            Price = 700.0,
                            Stock = 7,
                            SubCategoryId = 9
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Description = "Mechanical gaming keyboard",
                            ImageUrl = "keyboard_razer.jpg",
                            Name = "Razer BlackWidow",
                            Price = 150.0,
                            Stock = 20,
                            SubCategoryId = 10
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "Gaming mouse",
                            ImageUrl = "mouse_logitech.jpg",
                            Name = "Logitech G Pro X",
                            Price = 120.0,
                            Stock = 25,
                            SubCategoryId = 11
                        });
                });

            modelBuilder.Entity("TechCorner_ECommerce.Data.SubCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("SubCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Acer"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Asus"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "MSI"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Name = "Lenovo"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Name = "Gaming PC"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Name = "Workstation PC"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Name = "Mainboard"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Name = "CPU"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Name = "VGA"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Name = "Keyboard"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 4,
                            Name = "Mouse"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 4,
                            Name = "Headset"
                        });
                });

            modelBuilder.Entity("TechCorner_ECommerce.Data.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("TechCorner_ECommerce.Data.Order", b =>
                {
                    b.HasOne("TechCorner_ECommerce.Data.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TechCorner_ECommerce.Data.OrderItem", b =>
                {
                    b.HasOne("TechCorner_ECommerce.Data.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TechCorner_ECommerce.Data.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("TechCorner_ECommerce.Data.Product", b =>
                {
                    b.HasOne("TechCorner_ECommerce.Data.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TechCorner_ECommerce.Data.SubCategory", "SubCategory")
                        .WithMany("Products")
                        .HasForeignKey("SubCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("SubCategory");
                });

            modelBuilder.Entity("TechCorner_ECommerce.Data.SubCategory", b =>
                {
                    b.HasOne("TechCorner_ECommerce.Data.Category", "Category")
                        .WithMany("SubCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("TechCorner_ECommerce.Data.Category", b =>
                {
                    b.Navigation("Products");

                    b.Navigation("SubCategories");
                });

            modelBuilder.Entity("TechCorner_ECommerce.Data.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("TechCorner_ECommerce.Data.SubCategory", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("TechCorner_ECommerce.Data.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
